import turtle
t = turtle.Turtle()
t.pensize(5)
t.pencolor('deep sky blue')
for repc in range(1, 6):
    t.fd(23)
    t.pd()
    t.fd(23)
    t.pu()
t.pd()
t.lt(144)
t.pencolor('blue')
for repc in range(1, 6):
    t.fd(23)
    t.pd()
    t.fd(23)
    t.pu()
t.pd()
t.lt(144)
t.pencolor('green')
for repc in range(1, 6):
    t.fd(23)
    t.pd()
    t.fd(23)
    t.pu()
t.pd()
t.lt(144)
t.pencolor('red')
for repc in range(1, 6):
    t.fd(23)
    t.pd()
    t.fd(23)
    t.pu()
t.pd()
t.lt(144)
t.pencolor('YellowGreen')
for repc in range(1, 6):
    t.fd(23)
    t.pd()
    t.fd(23)
    t.pu()
t.pd()
t.lt(144)
turtle.done()
